### ISSUE TITLE
Fix the Link Logo for Twitter 

### ISSUE THREAD

**Issue by Mudassirkhan2** [DevMatrix1/CommunityWebsite#5]
Fix the Link Logo for Twitter  (screen Shot attached )
![Screenshot 2023-04-28 152006](https://user-images.githubusercontent.com/106579572/235115991-6d74555a-3042-4cd8-8bf4-c1e46171dce6.png)

**Comment by giri-madhan** [comment]
Hi @Mudassirkhan2 , Sorry I went ahead and created an PR for this issue as it was a simple fix. Could you please check if the PR changes are okay? - https://github.com/DevMatrix1/CommunityWebsite/pull/6
